services:
  db:
    image: postgres:18
    container_name: bookshelf-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookshelf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - bookshelf_pgdata:/var/lib/postgresql

volumes:
  bookshelf_pgdata:
