spring:
  datasource:
    url: jdbc:postgresql://db:5432/bookshelf
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  config:
    import: optional:file:../.env[.properties]

app:
  api-key: ${API_KEY}
  frontend-url: ${FRONTEND_URL}
  demo-shelf-public-id: ${DEMO_BOOKSHELF_PUBLIC_ID}
  seed-demo-shelf: true
