spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookshelf_test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    clean-disabled: false
  main:
    allow-bean-definition-overriding: true

app:
  api-key: test-key
  frontend-url: http://localhost:5173