spring:
  datasource:
    url: jdbc:sqlite:bookshelf.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  config:
    import: optional:file:.env[.properties]

app:
  api-key: ${API_KEY}
  frontend-url: ${FRONTEND_URL}
  demo-shelf-public-id: ${DEMO_BOOKSHELF_PUBLIC_ID}
  seed-demo-shelf: true
